//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION
    {
        public int ID_UTILI { get; set; }
        public int ID_CONTRAT_G { get; set; }
        public Nullable<int> TYPE_ACTION { get; set; }
        public Nullable<int> DATE_ACTION { get; set; }
        public Nullable<int> ID_ACTION { get; set; }
        public string TOUCHER { get; set; }
    }
}
