//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOMIBILE_RELATION_PERSON
    {
        public int ID_CONTRAT_AUTO { get; set; }
        public int ID_PERSONNE { get; set; }
        public string TYPE_RELATION { get; set; }
    }
}
