//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTRE_CONTRACT
    {
        public int ID_AUTRE_CONTRAT { get; set; }
        public int ID_COMP { get; set; }
        public string REF_CONTRACT { get; set; }
    }
}
