//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT
    {
        public int ID_CONTRAT_G { get; set; }
        public int ID_INTER { get; set; }
        public string N_CONTRAT { get; set; }
        public Nullable<int> DATE_CREATION { get; set; }
        public Nullable<int> DATE_ECHANCE { get; set; }
        public Nullable<int> DUREE_DE_CONTRAT { get; set; }
        public Nullable<double> PRIME_TOTAL { get; set; }
    }
}
