//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARANTIE
    {
        public int ID_GARANTIE { get; set; }
        public int ID_TYPE { get; set; }
        public string GARANTIE1 { get; set; }
        public string DESC_PUBLIC { get; set; }
    }
}
