//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERMEDIAIRE
    {
        public int ID_INTER { get; set; }
        public string INTER_NAME { get; set; }
        public string INTER_EMAIL { get; set; }
        public string INTER_ADRESSE { get; set; }
        public string INTER_TELEPHONE { get; set; }
        public string INTER_DESC { get; set; }
    }
}
