//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNE
    {
        public int ID_PERSONNE { get; set; }
        public Nullable<int> Fk_ID_SOURCE { get; set; }
        public Nullable<int> Fk_ID_VILLE { get; set; }
        public Nullable<int> Fk_ID_SEXE { get; set; }
        public Nullable<int> Fk_ID_TIDEN { get; set; }
        public Nullable<int> Fk_ID_PAYS { get; set; }
        public string NOM_COMPLET { get; set; }
        public Nullable<double> DATE_NAISS { get; set; }
        public string ADRESSE { get; set; }
        public string CODE_POSTAL { get; set; }
        public string N_TELEPHONE { get; set; }
        public string N_IDENT { get; set; }
        public string N_PIRME { get; set; }
        public string CATE_PERMI { get; set; }
        public Nullable<double> DATE_PERM { get; set; }
        public string ADRESSE_MAIL { get; set; }
    
        public virtual PAY PAY { get; set; }
        public virtual SOURCE_PERSONNE SOURCE_PERSONNE { get; set; }
        public virtual VILLE VILLE { get; set; }
        public virtual SEXE SEXE { get; set; }
        public virtual TYPE_IDENTITE TYPE_IDENTITE { get; set; }
    }
}
