//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING_UTILI
    {
        public int ID_SU { get; set; }
        public int ID_UTILI { get; set; }
        public string DEFAULT_SU { get; set; }
        public Nullable<int> TYPE_MENU { get; set; }
    }
}
