//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOURCE_PERSONNE
    {
        public SOURCE_PERSONNE()
        {
            this.PERSONNEs = new HashSet<PERSONNE>();
        }
    
        public int ID_SOURCE { get; set; }
        public Nullable<int> ID_TYPE_SOURCE { get; set; }
        public string NOM_SOURCE { get; set; }
        public string ADRESSE_SOURCE { get; set; }
        public string TELEPHONE_SOURCE { get; set; }
        public string EMAIL_SOURCE { get; set; }
    
        public virtual ICollection<PERSONNE> PERSONNEs { get; set; }
        public virtual TYPE_SOURCE TYPE_SOURCE { get; set; }
    }
}
