//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_SOURCE
    {
        public TYPE_SOURCE()
        {
            this.SOURCE_PERSONNE = new HashSet<SOURCE_PERSONNE>();
        }
    
        public int ID_TYPE_SOURCE { get; set; }
        public string TYPE_SOURCE1 { get; set; }
    
        public virtual ICollection<SOURCE_PERSONNE> SOURCE_PERSONNE { get; set; }
    }
}
