//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_IDENTITE
    {
        public TYPE_IDENTITE()
        {
            this.PERSONNEs = new HashSet<PERSONNE>();
        }
    
        public int ID_TIDEN { get; set; }
        public string TYPE_IDENTITE1 { get; set; }
    
        public virtual ICollection<PERSONNE> PERSONNEs { get; set; }
    }
}
