//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR_BLOOM
    {
        public int ID_UTILI { get; set; }
        public string NOM_UTIL { get; set; }
        public string MOTS_PASS_UTIL { get; set; }
        public Nullable<double> DATE_CREATION { get; set; }
        public Nullable<double> DATE_LAST_CNX { get; set; }
        public string N_TELE { get; set; }
        public string EMAIL { get; set; }
        public int Role { get; set; }
    }
}
