//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULE_ASSUREE
    {
        public int ID_VEH_ASSUREE { get; set; }
        public int ID_MARQUE { get; set; }
        public Nullable<int> ID_MODEL { get; set; }
        public string IMMATRICULATION { get; set; }
        public Nullable<int> PUIS_F { get; set; }
        public Nullable<int> PTC { get; set; }
        public Nullable<int> REMORQUE { get; set; }
        public Nullable<int> DMC { get; set; }
        public Nullable<int> MUTATION { get; set; }
        public Nullable<int> N_PLACES { get; set; }
        public string ORG_CREDI { get; set; }
        public Nullable<int> POTE_AV { get; set; }
        public Nullable<double> VALEUR_NEUF { get; set; }
        public Nullable<double> VALEUR_DECLAR { get; set; }
        public Nullable<double> VALEUR_GLACE { get; set; }
        public Nullable<double> VALEUR_AV { get; set; }
    }
}
