//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lebra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VILLE
    {
        public VILLE()
        {
            this.PERSONNEs = new HashSet<PERSONNE>();
        }
    
        public int ID_VILLE { get; set; }
        public string NOM_VILLE { get; set; }
        public Nullable<int> ID_PAYS { get; set; }
    
        public virtual PAY PAY { get; set; }
        public virtual ICollection<PERSONNE> PERSONNEs { get; set; }
    }
}
